### ISSUE TITLE
Cleanup of ecal.ini handling strategy

### ISSUE THREAD

**Issue by Kerstin-Keller** [continental/ecal#362]
`ecal.ini` loading strategy is not coherent.

### Installation:
eCAL.ini installed to
Windows: `C:/ProgramData/eCAL/ecal.ini`
Linux: `${CMAKE_INSTALL_PREFIX}/${sysconf_dir}/etc/ `-> ppa -> `/etc/ecal/ecal.ini`

### runtime
Prio: (Windows)
1. `$ECAL_DATA/ecal.ini`           (environment)
2. `$AppData/ecal/ecal.ini`     (user)
3. `$ProgramData/ecal/ecal.ini`   (global)

(Linux)
1. `HARDCODED_PATH/ecal.ini`       (hardcoded path, configured by cmake)

### Loading strategy
1. environment `$ECAL_DATA/ecal.ini`
2. User        `$HOME/.ecal/ecal.ini`   /  `$AppData/ecal/ecal.ini`   <---- (optional, to be deleted?)
3. System      `/etc/ecal/ecal.ini` (CMake variable)  / `$ProgramData/ecal/ecal.ini`  

### Installation strategy
- Windows: Part of Innosetup, needs a "keep" strategy
  - idea: Keyword in Innosetup  https://jrsoftware.org/ishelp/index.php?topic=filessection&anchor=onlyifdoesntexist
  - copy: `ecal.ini.new` (always copied, may be compared by user)
- Linux: `ecal.ini` marked as configuration file
  -> Not to be packaged in separate ecal-config.deb 😞  (still to be  discussed)

## Todo
This results in the following todo:
- [ ]  Add loading from `$ECAL_DATA/ecal.ini` for all platforms as highest priority
- [ ] Remove loading from `$AppData/ecal/ecal.ini`  
- [ ] Don't always overwrite ecal Settings from innosetup. See above.
- [ ] Add documentation on loading strategy

**Comment by rex-schilasky** [comment]
Don't close this issue .. documentation is still open.
